export const siteConfig = {
    title: 'klanservicehub',
    description: 'Enterprise project management, issue tracking, and team collaboration suite.',
    keywords: [
        'reactjs',
        'nextjs',
        'appwrite',
        'appwrite-io',
        'next-auth',
        'react-big-calendar',
        'lucide-icons',
        'react-icons',
        'react-day-picker',
        'shadcn-ui',
        'radix-ui',
        'tailwindcss',
        'lodash',
        'react-query',
        'nuqs',
        'sonner',
        'typescript',
        'javascript',
        'postcss',
        'prettier',
        'eslint',
        'react-dom',
        'html',
        'css',
        'nuqs-state-management',
        'infinite-query',
        'real-time-features',
        'organized-table',
        'filter-table',
        'paginate-table',
        'tasks-management',
        'projects-management',
        'workspaces-management',
        'ui/ux',
        'appwrite-db',
        'klanservicehub',
        'date-fns',
        'cn',
        'clsx',
        'lucide-react',
    ],
    authors: {
        name: 'KlanserviceHub Engineering',
        url: '#',
        github: '#',
        linkedin: '#',
        instagram: '#',
    },
};
export const links = {
    sourceCode: '#',
    portfolio: '#',
    linkedin: '#',
    instagram: '#',
};